title: Sinji's View
email: sinji@sakasin.net
description: >-
  酒田　シンジが気になったことをテキトーに書くブログ
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://sakasin.net"
twitter: ysakasin
github: ysakasin
permalink: /:title

# Build settings
markdown: kramdown
highlighter: rouge

# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
